/**
 * Created by giscafer on 2017/5/13.
 */

export const  PROJECTS: any = [
  {
    "type": ['home','plans'],
    "typeInfo": "【分享计划】",
    "img": "9",
    "title": "ng2-ife-course",
    "subtitle": "plans2",
    "meta": "百度前端技术学院demo演示SPA ",
    "description": "百度前端技术学院demo演示SPA ",
    "demoUrl": "",
    "routerLink": "/plans",
  },{
    "type": ['home','plans'],
    "typeInfo": "【分享计划】",
    "img": "7",
    "title": "physicaltable",
    "subtitle": "Java • BootStrap",
    "meta": "一个关于体育成绩登记的简单站点",
    "description": "一个关于体育成绩登记的简单站点",
    "demoUrl": "",
    "routerLink": "/plans",
  }, {
    "type": ['home','needs',''],
    "typeInfo": "【分享需求】",
    "img": "1",
    "title": "Ponitor",
    "subtitle": "intro.js1.x • ES6 • Node.js • MongoDB",
    "meta": " [ P ] rice + M [ onitor ] = Ponitor 价格监测应用",
    "description": "天猫、淘宝、京东、resourcele resource的商品，监控商品价格发生变动时（每天定时器），推送消息（目前是发送邮件）， 商品价格趋势分析统计等！",
    "demoUrl": "/needs",
    "routerLink": "/needs",
  },{
    "type": ['home','resource'],
    "typeInfo": "【学习资源】",
    "img": "3",
    "title": "GIS520",
    "subtitle": "php + H5",
    "meta": "大学时期创建GIS520论坛，开发的论坛H5 resource",
    "description": "大学时期创建GIS520论坛，开发的论坛H5 resource",
    "demoUrl": "",
    "routerLink": "/resource",
  },
  {
    "type": ['home','needs'],
    "typeInfo": "【分享需求】",
    "img": "2",
    "title": "needs-ponitor",
    "subtitle": "needs • needs-redux",
    "meta": " [ P ] rice + M [ onitor ] = Ponitor 价格监测应用",
    "description": "天猫、淘宝、京东、resourcele resource的商品，监控商品价格发生变动时（每天定时器），推送消息（目前是发送邮件），商品价格趋势分析统计等！",
    "demoUrl": "/needs",
    "routerLink": "/needs",
  },{
    "type": ['home','resource'],
    "typeInfo": "【学习资源】",
    "img": "6",
    "title": "mapshaper-plus",
    "subtitle": "HTML • CSS • JavaScript",
    "meta": "Generate geojson files for Echarts Map,base on mapshaper",
    "description": "基于mapshaper对geojson地图数据的坐标信息进行压缩编码，并提供可直接生成压缩编码后的echarts map数据格式，" +
    "通过mapshaper-plus可以直接将shp格式数据转换为压缩后的echarts数据",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home','resource'],
    "typeInfo": "【学习资源】",
    "img": "5",
    "title": "wechat-weresource-mapdemo",
    "subtitle": "HTML5 • CSS • JavaScript",
    "meta": "微信小程序开发demo，地图导航、marker标注",
    "description": "微信小程序开发demo，地图导航、marker标注",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home','plans'],
    "typeInfo": "【分享计划】",
    "img": "7",
    "title": "plans-chat",
    "subtitle": "plans4 • Node.js • Socket.io",
    "meta": "（IM resource）Chat resource built using plans and Socket.io",
    "description": "（IM resource）Chat resource built using plans and Socket.io，模仿百度E秘聊天",
    "demoUrl": "",
    "routerLink": "/plans",
  },{
    "type": ['home','needs'],
    "typeInfo": "【分享需求】",
    "img": "8",
    "title": "ife-course-demo",
    "subtitle": "needs",
    "meta": "百度前端技术学院demo演示SPA ",
    "description": "百度前端技术学院demo演示SPA ",
    "demoUrl": "/needs",
    "routerLink": "/needs",
  },{
    "type": ['home','resource'],
    "typeInfo": "【学习资源】",
    "img": "10",
    "title": "moviesite",
    "subtitle": "Node.js • Jade • MongoDB",
    "meta": "学习material时，开发的一个电影网站demo，功能包括注册登录，网站爬虫添加，电影查询删除等",
    "description": "学习material时，开发的一个电影网站demo，功能包括注册登录，爬虫添加电影，电影查询删除等",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home', 'resource'],
    "typeInfo": "【学习资源】",
    "img": "11",
    "title": "gisrobot",
    "subtitle": "Java • 微信公众号",
    "meta": " 微信公众号JAVA开发学习demo，天气预报查询、消息自动回复、中英文翻译",
    "description": "微信公众号开发机器人，天气预报查询、消息自动回复、中英文翻译",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home','resource'],
    "typeInfo": "【学习资源】",
    "img": "2",
    "title": "intro-order",
    "subtitle": "intro.js1.x • Node.js • MongoDB",
    "meta": " material+intro.js学习开发demo,订餐系统应用 ",
    "description": "material+intro.js学习开发demo,订餐系统应用",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home', 'resource', 'npm'],
    "typeInfo": "【学习资源】",
    "img": "3",
    "title": "node-ipcity",
    "subtitle": "NPM • Node.js",
    "meta": "Get ip city info 获取ip归属城市信息 | NPM插件",
    "description": "get ip city info 获取ip归属城市信息",
    "npm": "https://www.npmjs.com/package/node-ipcity",
    "demoUrl": "",
    "routerLink": "/resource",
  },{
    "type": ['home','plans'],
    "typeInfo": "【分享计划】",
    "img": "5",
    "title": "git-batch-file-builder",
    "subtitle": "plans1.x • Git • Node.js",
    "meta": "Git Batch File Builder，git批处理文件创建",
    "description": "Git Batch File Builder，git批处理文件创建",
    "demoUrl": "",
    "routerLink": "/plans",
  }
];
